import type { FsNode, FsService, NodeId, Revision } from "../../os/contracts/index.ts";

const encoder = new TextEncoder();
const decoder = new TextDecoder("utf-8", { fatal: true });
export interface DocumentSnapshot { nodeId: NodeId | null; name: string; text: string; dirty: boolean; status: "idle" | "loading" | "ready" | "saving" | "error" | "conflict"; error: string | null; }
export interface DocumentSessionOptions { autosaveMs?: number; }
interface FileStamp { id: NodeId; name: string; size: number; modifiedAt: number; contentHash?: string; mime?: string; parentId: NodeId | null; }
function stamp(node: FsNode): FileStamp { return { id: node.id, name: node.name, size: node.size, modifiedAt: node.modifiedAt, ...(node.contentHash ? { contentHash: node.contentHash } : {}), ...(node.mime ? { mime: node.mime } : {}), parentId: node.parentId }; }
/** Content identity check that does not treat rename/move metadata as a write conflict. */
export function sameFileContent(left: FileStamp, right: FileStamp): boolean { if (left.id !== right.id || left.size !== right.size) return false; if (left.contentHash !== undefined || right.contentHash !== undefined) return left.contentHash !== undefined && left.contentHash === right.contentHash; return left.modifiedAt === right.modifiedAt; }
export function utf8ByteLength(text: string): number { return encoder.encode(text).byteLength; }
export function cursorLineColumn(text: string, offset: number): { line: number; column: number } { const safe = Math.max(0, Math.min(offset, text.length)); const lines = text.slice(0, safe).split("\n"); return { line: lines.length, column: (lines.at(-1)?.length ?? 0) + 1 }; }
async function stableRead(fs: FsService, nodeId: NodeId): Promise<{ node: FsNode; text: string }> { for (let attempt = 0; attempt < 2; attempt += 1) { const before = await fs.stat(nodeId); const bytes = await fs.read(nodeId); const after = await fs.stat(nodeId); if (sameFileContent(stamp(before), stamp(after))) { try { return { node: after, text: decoder.decode(bytes) }; } catch { throw new Error(`${after.name || "File"} is not valid UTF-8`); } } } throw new Error("The file changed while it was being read. Try again."); }

export class DocumentSession {
  private readonly fs: FsService; private readonly autosaveMs: number; private readonly listeners = new Set<() => void>();
  private state: DocumentSnapshot = { nodeId: null, name: "", text: "", dirty: false, status: "idle", error: null };
  private baseline: FileStamp | null = null; private lastRevision: Revision | null = null; private generation = 0; private autosaveTimer: ReturnType<typeof setTimeout> | null = null; private disposed = false; private disposing = false; private autosaveSuspended = false; private suppressDisposeFlush = false;
  constructor(fs: FsService, options: DocumentSessionOptions = {}) { this.fs = fs; this.autosaveMs = options.autosaveMs ?? 750; }
  snapshot(): DocumentSnapshot { return { ...this.state }; }
  subscribe(listener: () => void): () => void { this.listeners.add(listener); return () => this.listeners.delete(listener); }
  private emit(): void { for (const listener of this.listeners) listener(); }
  private setState(patch: Partial<DocumentSnapshot>): void { this.state = { ...this.state, ...patch }; this.emit(); }
  private clearAutosave(): void { if (this.autosaveTimer !== null) { clearTimeout(this.autosaveTimer); this.autosaveTimer = null; } }
  private scheduleAutosave(): void { if (this.autosaveSuspended) return; this.clearAutosave(); const generation = this.generation; const nodeId = this.state.nodeId; this.autosaveTimer = setTimeout(() => { this.autosaveTimer = null; if (this.disposed || generation !== this.generation || nodeId !== this.state.nodeId) return; void this.save(); }, this.autosaveMs); }
  async setTarget(nodeId: NodeId | null): Promise<void> { this.clearAutosave(); this.autosaveSuspended = false; this.suppressDisposeFlush = false; const generation = ++this.generation; this.baseline = null; this.lastRevision = null; if (!nodeId) { this.setState({ nodeId: null, name: "", text: "", dirty: false, status: "idle", error: null }); return; } this.setState({ nodeId, name: "", text: "", dirty: false, status: "loading", error: null }); try { const loaded = await stableRead(this.fs, nodeId); const revision = await this.fs.revision(); if (this.disposed || generation !== this.generation) return; this.baseline = stamp(loaded.node); this.lastRevision = revision; this.setState({ nodeId, name: loaded.node.name, text: loaded.text, dirty: false, status: "ready", error: null }); } catch (error) { if (this.disposed || generation !== this.generation) return; this.setState({ status: "error", error: errorMessage(error) }); } }
  edit(text: string): void { if (this.disposed || this.state.nodeId === null || this.state.status === "loading") return; this.suppressDisposeFlush = false; this.setState({ text, dirty: true, status: "ready", error: null }); this.scheduleAutosave(); }
  suspendAutosave(): void { if (this.disposed) return; this.autosaveSuspended = true; this.clearAutosave(); }
  resumeAutosave(): void { if (this.disposed) return; const wasSuspended = this.autosaveSuspended; this.autosaveSuspended = false; if (wasSuspended && this.state.dirty && this.state.status === "ready") this.scheduleAutosave(); }
  discardOnClose(): void { if (this.disposed) return; this.clearAutosave(); this.autosaveSuspended = true; this.suppressDisposeFlush = true; }
  private async hasExternalContentChange(nodeId: NodeId): Promise<{ changed: boolean; node: FsNode }> { const node = await this.fs.stat(nodeId); if (!this.baseline) return { changed: false, node }; return { changed: !sameFileContent(this.baseline, stamp(node)), node }; }
  async save(): Promise<boolean> { this.clearAutosave(); if (this.disposed || !this.state.nodeId || !this.state.dirty) return !this.state.dirty; const generation = this.generation; const nodeId = this.state.nodeId; const text = this.state.text; try { const external = await this.hasExternalContentChange(nodeId); if (this.disposed || generation !== this.generation || nodeId !== this.state.nodeId) return false; if (external.changed) { this.setState({ status: "conflict", error: "This file changed outside the editor. Reload it or explicitly overwrite the newer version." }); return false; } this.setState({ status: "saving", error: null }); const written = await this.fs.write(nodeId, encoder.encode(text), { truncate: true }); const revision = await this.fs.revision(); if (this.disposed || generation !== this.generation || nodeId !== this.state.nodeId) return true; this.baseline = stamp(written); this.lastRevision = revision; this.suppressDisposeFlush = false; this.setState({ name: written.name, dirty: false, status: "ready", error: null }); return true; } catch (error) { if (!this.disposed && generation === this.generation && nodeId === this.state.nodeId) this.setState({ status: "error", error: `Save failed: ${errorMessage(error)}` }); return false; } }
  async forceSave(): Promise<boolean> { if (!this.state.nodeId || !this.state.dirty) return false; try { this.baseline = stamp(await this.fs.stat(this.state.nodeId)); this.setState({ status: "ready", error: null }); return await this.save(); } catch (error) { this.setState({ status: "error", error: errorMessage(error) }); return false; } }
  async reload(): Promise<void> { await this.setTarget(this.state.nodeId); }
  async checkExternalChange(): Promise<boolean> { const nodeId = this.state.nodeId; if (this.disposed || !nodeId || !this.baseline || this.state.status === "loading" || this.state.status === "saving") return false; try { const revision = await this.fs.revision(); if (this.lastRevision !== null && revision === this.lastRevision) return false; const node = await this.fs.stat(nodeId); const nextStamp = stamp(node); this.lastRevision = revision; if (sameFileContent(this.baseline, nextStamp)) { this.baseline = nextStamp; if (node.name !== this.state.name) this.setState({ name: node.name }); return false; } if (this.state.dirty) { this.setState({ status: "conflict", error: "A newer filesystem revision exists. Your unsaved edits have not overwritten it." }); return true; } await this.setTarget(nodeId); return true; } catch (error) { this.setState({ status: "error", error: `Filesystem refresh failed: ${errorMessage(error)}` }); return false; } }
  async saveAs(name: string, mime = "text/plain"): Promise<FsNode> { const trimmed = name.trim(); if (!trimmed || /[\\/\0]/.test(trimmed)) throw new Error("Choose a valid file name"); const nodeId = this.state.nodeId; if (!nodeId) throw new Error("No file is open"); const source = await this.fs.stat(nodeId); if (source.parentId === null) throw new Error("Cannot save beside the filesystem root"); const created = await this.fs.createFile(source.parentId, trimmed, { mime: source.mime ?? mime }); try { const written = await this.fs.write(created.id, encoder.encode(this.state.text), { truncate: true }); await this.setTarget(written.id); return written; } catch (error) { try { await this.fs.remove(created.id); } catch { /* best-effort rollback */ } throw error; } }
  dispose(options: { flush?: boolean } = {}): void { if (this.disposed || this.disposing) return; this.clearAutosave(); this.listeners.clear(); if (options.flush && !this.suppressDisposeFlush && this.state.dirty && this.state.status !== "conflict") { this.disposing = true; void this.save().finally(() => { this.disposed = true; this.disposing = false; this.generation += 1; }); return; } this.disposed = true; this.generation += 1; }
}
export function errorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
