import esbuild from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

const MONACO_WORKERS = [
  ["editor.worker.js", "monaco-editor/esm/vs/editor/editor.worker.js"],
  ["json.worker.js", "monaco-editor/esm/vs/language/json/json.worker.js"],
  ["css.worker.js", "monaco-editor/esm/vs/language/css/css.worker.js"],
  ["html.worker.js", "monaco-editor/esm/vs/language/html/html.worker.js"],
  ["ts.worker.js", "monaco-editor/esm/vs/language/typescript/ts.worker.js"],
] as const;

const GENERATED_RUNTIME_ROOT = "./public/runtime/monaco";
const GENERATED_CANONICAL_ROOT = "./public/System/Program Files/MonacoEditor";
const GENERATED_TRANSPORT = `${GENERATED_RUNTIME_ROOT}/worker-sources.js`;
const CANONICAL_OUTPUT_ROOT = "System/Program Files/MonacoEditor";

async function bundleWorker(filename: string, entryPoint: string, devMode: boolean): Promise<string> {
  const outputName = filename.replace(/\.js$/, "");
  const result = await esbuild.build({
    entryPoints: [{ in: entryPoint, out: `${CANONICAL_OUTPUT_ROOT}/${outputName}` }],
    outdir: "./dist/web",
    bundle: true,
    write: false,
    minify: !devMode,
    sourcemap: devMode ? "inline" : false,
    external: [],
    // Keep one self-contained worker byte stream that is valid both as a normal
    // module Worker script and as the classic blob transport required by
    // Neutron's opaque-origin application sandbox.
    format: "iife",
    jsx: "automatic",
    loader: { ".ts": "ts", ".tsx": "tsx", ".ttf": "file" },
    platform: "browser",
    logLevel: "silent",
  });

  const canonicalSuffix = `/${CANONICAL_OUTPUT_ROOT}/${filename}`;
  const workerOutput = result.outputFiles?.find((file) =>
    file.path.replaceAll("\\", "/").endsWith(canonicalSuffix)
  );
  if (!workerOutput) {
    const outputs = result.outputFiles?.map((file) => file.path).join(", ") ?? "none";
    throw new Error(`Monaco worker transport did not emit ${filename}; outputs: ${outputs}`);
  }
  return workerOutput.text;
}

const sources: Record<string, string> = {};
for (const [filename, entryPoint] of MONACO_WORKERS) {
  sources[filename] = await bundleWorker(filename, entryPoint, process.argv.includes("dev"));
}

const script = [
  "/* Generated by monacoWorkerTransport.ts. Do not edit or commit this file. */",
  "(() => {",
  "  const scope = globalThis;",
  `  const sources = Object.freeze(${JSON.stringify(sources)});`,
  "  Object.defineProperty(scope, \"__PLASMON_MONACO_WORKER_SOURCES__\", {",
  "    configurable: false,",
  "    enumerable: false,",
  "    writable: false,",
  "    value: sources,",
  "  });",
  "",
  "  if (scope.MonacoEnvironment?.getWorker) return;",
  "  const workerFile = (label) => {",
  "    if (label === \"json\") return \"json.worker.js\";",
  "    if (label === \"css\" || label === \"scss\" || label === \"less\") return \"css.worker.js\";",
  "    if (label === \"html\" || label === \"handlebars\" || label === \"razor\") return \"html.worker.js\";",
  "    if (label === \"typescript\" || label === \"javascript\") return \"ts.worker.js\";",
  "    return \"editor.worker.js\";",
  "  };",
  "  const current = scope.MonacoEnvironment ?? {};",
  "  scope.MonacoEnvironment = {",
  "    ...current,",
  "    getWorker(_moduleId, label) {",
  "      const filename = workerFile(label);",
  "      const name = `plasmon-monaco-${label || \"editor\"}`;",
  "      if (scope.origin !== \"null\") {",
  "        return new scope.Worker(`./System/Program Files/MonacoEditor/${filename}`, { type: \"module\", name });",
  "      }",
  "      const source = sources[filename];",
  "      if (!source) throw new Error(`Missing packaged Monaco worker source: ${filename}`);",
  "      const bootstrap = new scope.Blob([source], { type: \"text/javascript\" });",
  "      const bootstrapUrl = scope.URL.createObjectURL(bootstrap);",
  "      try {",
  "        return new scope.Worker(bootstrapUrl, { name });",
  "      } catch (error) {",
  "        scope.URL.revokeObjectURL(bootstrapUrl);",
  "        throw error;",
  "      }",
  "    },",
  "  };",
  "})();",
  "",
].join("\n");

// build.ts emits worker entry points so the package metafile continues to prove
// their presence. The static-file copy step runs after esbuild output and
// deliberately replaces those transport copies with these canonical IIFE bytes.
// That leaves Program Files, the URL-safe mirror, and the opaque-frame preload
// derived from one exact byte stream while keeping main.js in ESM format. The
// preload also installs MonacoEnvironment before main.js executes so Monaco's
// bundled modules cannot observe an unconfigured worker factory during startup.
await Promise.all([
  mkdir(GENERATED_CANONICAL_ROOT, { recursive: true }),
  mkdir(GENERATED_RUNTIME_ROOT, { recursive: true }),
]);
await Promise.all(
  Object.entries(sources).flatMap(([filename, source]) => [
    writeFile(`${GENERATED_CANONICAL_ROOT}/${filename}`, source),
    writeFile(`${GENERATED_RUNTIME_ROOT}/${filename}`, source),
  ]),
);
await mkdir(dirname(GENERATED_TRANSPORT), { recursive: true });
await writeFile(GENERATED_TRANSPORT, script);
