import esbuild from "esbuild";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { resolvePackageProfile } from "./packageProfilePolicy.ts";

const ALL_MONACO_WORKERS = [
  ["editor.worker.js", "monaco-editor/esm/vs/editor/editor.worker.js"],
  ["json.worker.js", "monaco-editor/esm/vs/language/json/json.worker.js"],
  ["css.worker.js", "monaco-editor/esm/vs/language/css/css.worker.js"],
  ["html.worker.js", "monaco-editor/esm/vs/language/html/html.worker.js"],
  ["ts.worker.js", "monaco-editor/esm/vs/language/typescript/ts.worker.js"],
] as const;
const packagePolicy = resolvePackageProfile();
const MONACO_WORKERS = packagePolicy.monacoProfile === "slim"
  ? ALL_MONACO_WORKERS.slice(0, 1)
  : ALL_MONACO_WORKERS;

const GENERATED_RUNTIME_ROOT = "./public/runtime/monaco";
const GENERATED_CANONICAL_ROOT = "./public/System/Program Files/MonacoEditor";
const GENERATED_TRANSPORT = `${GENERATED_RUNTIME_ROOT}/worker-sources.js`;
const CANONICAL_OUTPUT_ROOT = "System/Program Files/MonacoEditor";

async function bundleWorker(filename: string, entryPoint: string, devMode: boolean): Promise<string> {
  const outputName = filename.replace(/\.js$/, "");
  const result = await esbuild.build({
    entryPoints: [{ in: entryPoint, out: `${CANONICAL_OUTPUT_ROOT}/${outputName}` }],
    outdir: "./dist/web",
    bundle: true,
    write: false,
    minify: !devMode,
    sourcemap: devMode ? "inline" : false,
    external: [],
    // Keep one self-contained worker byte stream that is valid both as a normal
    // module Worker script and as the classic blob transport required by
    // Neutron's opaque-origin application sandbox.
    format: "iife",
    jsx: "automatic",
    loader: { ".ts": "ts", ".tsx": "tsx", ".ttf": "file" },
    platform: "browser",
    logLevel: "silent",
  });

  const canonicalSuffix = `/${CANONICAL_OUTPUT_ROOT}/${filename}`;
  const workerOutput = result.outputFiles?.find((file) =>
    file.path.replaceAll("\\", "/").endsWith(canonicalSuffix)
  );
  if (!workerOutput) {
    const outputs = result.outputFiles?.map((file) => file.path).join(", ") ?? "none";
    throw new Error(`Monaco worker transport did not emit ${filename}; outputs: ${outputs}`);
  }
  return workerOutput.text;
}

const sources: Record<string, string> = {};
for (const [filename, entryPoint] of MONACO_WORKERS) {
  sources[filename] = await bundleWorker(filename, entryPoint, process.argv.includes("dev"));
}

const script = [
  "/* Generated by monacoWorkerTransport.ts. Do not edit or commit this file. */",
  "Object.defineProperty(globalThis, \"__PLASMON_MONACO_WORKER_SOURCES__\", {",
  "  configurable: false,",
  "  enumerable: false,",
  "  writable: false,",
  `  value: Object.freeze(${JSON.stringify(sources)}),`,
  "});",
  "",
].join("\n");

// Program Files is the canonical worker authority. Opaque Neutron frames need
// the generated source preload because they cannot construct Monaco's module
// Worker directly. Base retains URL-safe worker mirrors for its packaged
// language-service acceptance; Slim does not need the redundant mirror because
// its production paths are Program Files (normal origin) and the preload
// (opaque origin).
await Promise.all([
  rm(GENERATED_CANONICAL_ROOT, { recursive: true, force: true }),
  rm(GENERATED_RUNTIME_ROOT, { recursive: true, force: true }),
]);
await Promise.all([
  mkdir(GENERATED_CANONICAL_ROOT, { recursive: true }),
  mkdir(GENERATED_RUNTIME_ROOT, { recursive: true }),
]);
await Promise.all(
  Object.entries(sources).flatMap(([filename, source]) => [
    writeFile(`${GENERATED_CANONICAL_ROOT}/${filename}`, source),
    ...(packagePolicy.monacoProfile === "slim"
      ? []
      : [writeFile(`${GENERATED_RUNTIME_ROOT}/${filename}`, source)]),
  ]),
);
await mkdir(dirname(GENERATED_TRANSPORT), { recursive: true });
await writeFile(GENERATED_TRANSPORT, script);
