import esbuild from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

const MONACO_WORKERS = [
  ["editor.worker.js", "monaco-editor/esm/vs/editor/editor.worker.js"],
  ["json.worker.js", "monaco-editor/esm/vs/language/json/json.worker.js"],
  ["css.worker.js", "monaco-editor/esm/vs/language/css/css.worker.js"],
  ["html.worker.js", "monaco-editor/esm/vs/language/html/html.worker.js"],
  ["ts.worker.js", "monaco-editor/esm/vs/language/typescript/ts.worker.js"],
] as const;

const GENERATED_TRANSPORT = "./public/runtime/monaco/worker-sources.js";

async function bundleWorker(entryPoint: string, devMode: boolean): Promise<string> {
  const result = await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    write: false,
    minify: !devMode,
    sourcemap: devMode ? "inline" : false,
    external: [],
    format: "esm",
    jsx: "automatic",
    loader: { ".ts": "ts", ".tsx": "tsx", ".ttf": "file" },
    platform: "browser",
    logLevel: "silent",
  });
  if (!result.outputFiles || result.outputFiles.length !== 1) {
    throw new Error(`Monaco worker transport expected one bundled output for ${entryPoint}`);
  }
  return result.outputFiles[0]!.text;
}

const sources: Record<string, string> = {};
for (const [filename, entryPoint] of MONACO_WORKERS) {
  sources[filename] = await bundleWorker(entryPoint, process.argv.includes("dev"));
}

const script = [
  "/* Generated by monacoWorkerTransport.ts. Do not edit or commit this file. */",
  "Object.defineProperty(globalThis, \"__PLASMON_MONACO_WORKER_SOURCES__\", {",
  "  configurable: false,",
  "  enumerable: false,",
  "  writable: false,",
  `  value: Object.freeze(${JSON.stringify(sources)}),`,
  "});",
  "",
].join("\n");

await mkdir(dirname(GENERATED_TRANSPORT), { recursive: true });
await writeFile(GENERATED_TRANSPORT, script);
